### ISSUE TITLE
Damien is leaving

### ISSUE THREAD

**Issue by tombola** [ucfalmouth/Problem-Wall#1]

**Comment by damienh** [comment]
I dont see this as an issue :P

**Comment by tombola** [comment]
I do : (

Only an issue for Problem Wall app if not picked up elsewhere or if your replacement doesn't do ruby/rails

**Comment by damienh** [comment]
thats not up to me. They can learn what they like.

**Comment by tombola** [comment]
True. Will still miss your effervescent enthusiasm though
